version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: electron-releaser
    ports:
      - 8080:80
    volumes:
      - ./www:/var/www
    links:
      - mysql
    environment:
      DB_HOSTNAME: localhost
      DB_DATABASE: electron_releaser
      DB_USERNAME: root
      DB_PASSWORD: root

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./.docker:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    links:
      - mysql
